PROGRAMS = Get.class Next.class Options.class Follow.class \
	   DirectFollow.class  Nominus.class Flags.class \
	   InputFile.class Variables.class Filter.class \
  	   Expand.class Ufo.class


all: $(PROGRAMS) 

%.class: %.java
	javac $< 

clean:
	rm $(PROGRAMS)
